debug: false
uuid: 231ad4c4-d1c7-4071-b2fe-cf722e2c780e
token_id: O90mK5zrJQRdD1Ck
token: of88Rnd6WWAhdMqXUUxk0AYevTcH7weJNebPWhqWcFKxWrMBBTHwLhGZBb5gu2MQ
api:
  host: 0.0.0.0
  port: 443
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/lemming-deciding-reindeer.ngrok-free.app/fullchain.pem
    key: /etc/letsencrypt/live/lemming-deciding-reindeer.ngrok-free.app/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://silver-train-9r7p5x4474c99jg-80.app.github.dev'
